//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int codigo_personal { get; set; }
        public string documento { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public Nullable<short> activo_sn { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
